/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BottomBar: typeof import('./src/components/BottomBar.vue')['default']
    ButtonIcon: typeof import('./src/components/ButtonIcon.vue')['default']
    CardList: typeof import('./src/components/CardList.vue')['default']
    ContentLoader: typeof import('./src/components/ContentLoader.vue')['default']
    Divide: typeof import('./src/components/Divide.vue')['default']
    LinkTo: typeof import('./src/components/LinkTo.vue')['default']
    Menu: typeof import('./src/components/ContextMenu/menu.vue')['default']
    Message: typeof import('./src/components/Message/message.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PlList: typeof import('./src/components/PlList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    WyLoading: typeof import('./src/components/WyLoading.vue')['default']
  }
}
